spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budget-manager-backend
    username: akshay
    password: akshay
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080